name: Invitation to the GitHub Organization
description: I would like to be part of the Elevance Innovation Technology
title: "Please invite me to the GitHub Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your Name here
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email
      placeholder: Insert your Email here
    validations:
      required: true
  - type: input
    id: phone
    attributes:
      label: Phone (if applicable)
      placeholder: Insert your Phone here
    validations:
      required: false
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: Where did you meet Elevance Innovation Technology?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        You can also join our Slack community [here](https://join.slack.com/t/elevance-it/shared_invite/zt-2tcaaivlf-5QxRlx2sXSSDuZHSkAk0xQ)
